### ISSUE TITLE
Belgrade theme should hide title block on product pages

### ISSUE THREAD

**Issue by mglaman** [drupalcommerce/demo-project#12]
See config in profile

```
visibility:
  request_path:
    id: request_path
    pages: '/product/*'
    negate: true
    context_mapping: {  }
```

The theme styles the product title to be inline, so the title block should hide itself.
